// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://efngefptdpovpqxfhmcx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVmbmdlZnB0ZHBvdnBxeGZobWN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwMTkwNjYsImV4cCI6MjA3MTU5NTA2Nn0.3VZbJz39Q8dbAWLKb9ZxzqqgPyYAUj06puQAY00aM3M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});